const data = [
  { name: "faqweqwk", id: 1 },
  { name: "asdsde", id: 2 },
  { name: "deas", id: 3 },
  { name: "wewe", id: 4 },
  { name: "fdsasaak", id: 5 },
  { name: "dsadas", id: 6 },
  { name: "aqwe1", id: 7 },
  { name: "asdasd", id: 8 },
  { name: "dsadsad", id: 9 },
  { name: "sadsa", id: 10 },
  { name: "cscvxcv", id: 11 },
  { name: "fvxcvxak", id: 12 },
  { name: "f cxvxck", id: 13 },
  { name: "favcxvfk", id: 14 },
  { name: "favfk", id: 15 },
  { name: "fvxvccak", id: 16 },
  { name: "f cx ak", id: 17 },
  { name: "fcvdak", id: 18 },
  { name: "fdfsdak", id: 19 },
  { name: "fvdsvsak", id: 20 },
  { name: "fvdsvak", id: 21 },
  { name: "fvdsvak", id: 22 },
];
